<?xml version="1.0" encoding="UTF-8" standalone="yes" ?><?codewarrior exportversion="1.0.1" ideversion="4.1" ?><!DOCTYPE PROJECT [<!ELEMENT PROJECT (TARGETLIST, TARGETORDER, GROUPLIST, DESIGNLIST?)><!ELEMENT TARGETLIST (TARGET+)><!ELEMENT TARGET (NAME, SETTINGLIST, FILELIST?, LINKORDER?, SEGMENTLIST?, OVERLAYGROUPLIST?, SUBTARGETLIST?, SUBPROJECTLIST?)><!ELEMENT NAME (#PCDATA)><!ELEMENT USERSOURCETREETYPE (#PCDATA)><!ELEMENT PATH (#PCDATA)><!ELEMENT FILELIST (FILE*)><!ELEMENT FILE (PATHTYPE, PATHROOT?, ACCESSPATH?, PATH, PATHFORMAT?, ROOTFILEREF?, FILEKIND?, FILEFLAGS?)><!ELEMENT PATHTYPE (#PCDATA)><!ELEMENT PATHROOT (#PCDATA)><!ELEMENT ACCESSPATH (#PCDATA)><!ELEMENT PATHFORMAT (#PCDATA)><!ELEMENT ROOTFILEREF (PATHTYPE, PATHROOT?, ACCESSPATH?, PATH, PATHFORMAT?)><!ELEMENT FILEKIND (#PCDATA)><!ELEMENT FILEFLAGS (#PCDATA)><!ELEMENT FILEREF (TARGETNAME?, PATHTYPE, PATHROOT?, ACCESSPATH?, PATH, PATHFORMAT?)><!ELEMENT TARGETNAME (#PCDATA)><!ELEMENT SETTINGLIST ((SETTING|PANELDATA)+)><!ELEMENT SETTING (NAME?, (VALUE|(SETTING+)))><!ELEMENT PANELDATA (NAME, VALUE)><!ELEMENT VALUE (#PCDATA)><!ELEMENT LINKORDER (FILEREF*)><!ELEMENT SEGMENTLIST (SEGMENT+)><!ELEMENT SEGMENT (NAME, ATTRIBUTES?, FILEREF*)><!ELEMENT ATTRIBUTES (#PCDATA)><!ELEMENT OVERLAYGROUPLIST (OVERLAYGROUP+)><!ELEMENT OVERLAYGROUP (NAME, BASEADDRESS, OVERLAY*)><!ELEMENT BASEADDRESS (#PCDATA)><!ELEMENT OVERLAY (NAME, FILEREF*)><!ELEMENT SUBTARGETLIST (SUBTARGET+)><!ELEMENT SUBTARGET (TARGETNAME, ATTRIBUTES?, FILEREF?)><!ELEMENT SUBPROJECTLIST (SUBPROJECT+)><!ELEMENT SUBPROJECT (FILEREF, SUBPROJECTTARGETLIST)><!ELEMENT SUBPROJECTTARGETLIST (SUBPROJECTTARGET*)><!ELEMENT SUBPROJECTTARGET (TARGETNAME, ATTRIBUTES?, FILEREF?)><!ELEMENT TARGETORDER (ORDEREDTARGET|ORDEREDDESIGN)*><!ELEMENT ORDEREDTARGET (NAME)><!ELEMENT ORDEREDDESIGN (NAME, ORDEREDTARGET+)><!ELEMENT GROUPLIST (GROUP|FILEREF)*><!ELEMENT GROUP (NAME, (GROUP|FILEREF)*)><!ELEMENT DESIGNLIST (DESIGN+)><!ELEMENT DESIGN (NAME, DESIGNDATA)><!ELEMENT DESIGNDATA (#PCDATA)>]><PROJECT>    <TARGETLIST>        <TARGET>            <NAME>TclapplescriptShLib</NAME>            <SETTINGLIST>                <!-- Settings for "Source Trees" panel -->                <SETTING><NAME>UserSourceTrees</NAME><VALUE></VALUE></SETTING>                <!-- Settings for "Access Paths" panel -->                <SETTING><NAME>AlwaysSearchUserPaths</NAME><VALUE>true</VALUE></SETTING>                <SETTING><NAME>InterpretDOSAndUnixPaths</NAME><VALUE>false</VALUE></SETTING>                <SETTING><NAME>UserSearchPaths</NAME>                    <SETTING>                        <SETTING><NAME>SearchPath</NAME>                            <SETTING><NAME>Path</NAME><VALUE>:</VALUE></SETTING>                            <SETTING><NAME>PathFormat</NAME><VALUE>MacOS</VALUE></SETTING>                            <SETTING><NAME>PathRoot</NAME><VALUE>Project</VALUE></SETTING>                        </SETTING>                        <SETTING><NAME>Recursive</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>SearchPath</NAME>                            <SETTING><NAME>Path</NAME><VALUE>::</VALUE></SETTING>                            <SETTING><NAME>PathFormat</NAME><VALUE>MacOS</VALUE></SETTING>                            <SETTING><NAME>PathRoot</NAME><VALUE>Project</VALUE></SETTING>                        </SETTING>                        <SETTING><NAME>Recursive</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>SearchPath</NAME>                            <SETTING><NAME>Path</NAME><VALUE>:::tcl:mac:</VALUE></SETTING>                            <SETTING><NAME>PathFormat</NAME><VALUE>MacOS</VALUE></SETTING>                            <SETTING><NAME>PathRoot</NAME><VALUE>Project</VALUE></SETTING>                        </SETTING>                        <SETTING><NAME>Recursive</NAME><VALUE>true</VALUE></SETTING>                        <SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>SearchPath</NAME>                            <SETTING><NAME>Path</NAME><VALUE>:::tcl:generic:</VALUE></SETTING>                            <SETTING><NAME>PathFormat</NAME><VALUE>MacOS</VALUE></SETTING>                            <SETTING><NAME>PathRoot</NAME><VALUE>Project</VALUE></SETTING>                        </SETTING>                        <SETTING><NAME>Recursive</NAME><VALUE>true</VALUE></SETTING>                        <SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>                    </SETTING>                </SETTING>                <SETTING><NAME>SystemSearchPaths</NAME>                    <SETTING>                        <SETTING><NAME>SearchPath</NAME>                            <SETTING><NAME>Path</NAME><VALUE>:MacOS Support:</VALUE></SETTING>                            <SETTING><NAME>PathFormat</NAME><VALUE>MacOS</VALUE></SETTING>                            <SETTING><NAME>PathRoot</NAME><VALUE>CodeWarrior</VALUE></SETTING>                        </SETTING>                        <SETTING><NAME>Recursive</NAME><VALUE>true</VALUE></SETTING>                        <SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>SearchPath</NAME>                            <SETTING><NAME>Path</NAME><VALUE>:MSL:</VALUE></SETTING>                            <SETTING><NAME>PathFormat</NAME><VALUE>MacOS</VALUE></SETTING>                            <SETTING><NAME>PathRoot</NAME><VALUE>CodeWarrior</VALUE></SETTING>                        </SETTING>                        <SETTING><NAME>Recursive</NAME><VALUE>true</VALUE></SETTING>                        <SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>SearchPath</NAME>                            <SETTING><NAME>Path</NAME><VALUE>:::tcl:compat:</VALUE></SETTING>                            <SETTING><NAME>PathFormat</NAME><VALUE>MacOS</VALUE></SETTING>                            <SETTING><NAME>PathRoot</NAME><VALUE>Project</VALUE></SETTING>                        </SETTING>                        <SETTING><NAME>Recursive</NAME><VALUE>true</VALUE></SETTING>                        <SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>SearchPath</NAME>                            <SETTING><NAME>Path</NAME><VALUE>:::MoreFiles:</VALUE></SETTING>                            <SETTING><NAME>PathFormat</NAME><VALUE>MacOS</VALUE></SETTING>                            <SETTING><NAME>PathRoot</NAME><VALUE>Project</VALUE></SETTING>                        </SETTING>                        <SETTING><NAME>Recursive</NAME><VALUE>true</VALUE></SETTING>                        <SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>                    </SETTING>                </SETTING>                <!-- Settings for "Debugger Runtime" panel -->                <SETTING><NAME>MWRuntimeSettings_WorkingDirectory</NAME><VALUE></VALUE></SETTING>                <SETTING><NAME>MWRuntimeSettings_CommandLine</NAME><VALUE></VALUE></SETTING>                <SETTING><NAME>MWRuntimeSettings_HostApplication</NAME>                    <SETTING><NAME>Path</NAME><VALUE></VALUE></SETTING>                    <SETTING><NAME>PathFormat</NAME><VALUE>Generic</VALUE></SETTING>                    <SETTING><NAME>PathRoot</NAME><VALUE>Absolute</VALUE></SETTING>                </SETTING>                <SETTING><NAME>MWRuntimeSettings_EnvVars</NAME><VALUE></VALUE></SETTING>                <!-- Settings for "Target Settings" panel -->                <SETTING><NAME>Linker</NAME><VALUE>MacOS Merge</VALUE></SETTING>                <SETTING><NAME>PreLinker</NAME><VALUE></VALUE></SETTING>                <SETTING><NAME>PostLinker</NAME><VALUE></VALUE></SETTING>                <SETTING><NAME>Targetname</NAME><VALUE>TclapplescriptShLib</VALUE></SETTING>                <SETTING><NAME>OutputDirectory</NAME>                    <SETTING><NAME>Path</NAME><VALUE>::</VALUE></SETTING>                    <SETTING><NAME>PathFormat</NAME><VALUE>MacOS</VALUE></SETTING>                    <SETTING><NAME>PathRoot</NAME><VALUE>Project</VALUE></SETTING>                </SETTING>                <SETTING><NAME>SaveEntriesUsingRelativePaths</NAME><VALUE>false</VALUE></SETTING>                <!-- Settings for "File Mappings" panel -->                <SETTING><NAME>FileMappings</NAME>                    <SETTING>                        <SETTING><NAME>FileType</NAME><VALUE>APPL</VALUE></SETTING>                        <SETTING><NAME>FileExtension</NAME><VALUE></VALUE></SETTING>                        <SETTING><NAME>Compiler</NAME><VALUE></VALUE></SETTING>                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>Launchable</NAME><VALUE>true</VALUE></SETTING>                        <SETTING><NAME>ResourceFile</NAME><VALUE>true</VALUE></SETTING>                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>FileType</NAME><VALUE>Appl</VALUE></SETTING>                        <SETTING><NAME>FileExtension</NAME><VALUE></VALUE></SETTING>                        <SETTING><NAME>Compiler</NAME><VALUE></VALUE></SETTING>                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>Launchable</NAME><VALUE>true</VALUE></SETTING>                        <SETTING><NAME>ResourceFile</NAME><VALUE>true</VALUE></SETTING>                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>FileType</NAME><VALUE>RSRC</VALUE></SETTING>                        <SETTING><NAME>FileExtension</NAME><VALUE></VALUE></SETTING>                        <SETTING><NAME>Compiler</NAME><VALUE></VALUE></SETTING>                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>Launchable</NAME><VALUE>true</VALUE></SETTING>                        <SETTING><NAME>ResourceFile</NAME><VALUE>true</VALUE></SETTING>                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>                        <SETTING><NAME>FileExtension</NAME><VALUE>.bh</VALUE></SETTING>                        <SETTING><NAME>Compiler</NAME><VALUE>Balloon Help</VALUE></SETTING>                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>                        <SETTING><NAME>FileExtension</NAME><VALUE>.r</VALUE></SETTING>                        <SETTING><NAME>Compiler</NAME><VALUE>Rez</VALUE></SETTING>                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>FileType</NAME><VALUE>rsrc</VALUE></SETTING>                        <SETTING><NAME>FileExtension</NAME><VALUE></VALUE></SETTING>                        <SETTING><NAME>Compiler</NAME><VALUE></VALUE></SETTING>                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>Launchable</NAME><VALUE>true</VALUE></SETTING>                        <SETTING><NAME>ResourceFile</NAME><VALUE>true</VALUE></SETTING>                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>FileType</NAME><VALUE>shlb</VALUE></SETTING>                        <SETTING><NAME>FileExtension</NAME><VALUE></VALUE></SETTING>                        <SETTING><NAME>Compiler</NAME><VALUE></VALUE></SETTING>                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>ResourceFile</NAME><VALUE>true</VALUE></SETTING>                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>                    </SETTING>                </SETTING>                <!-- Settings for "Build Extras" panel -->                <SETTING><NAME>CacheModDates</NAME><VALUE>true</VALUE></SETTING>                <SETTING><NAME>ActivateBrowser</NAME><VALUE>false</VALUE></SETTING>                <SETTING><NAME>DumpBrowserInfo</NAME><VALUE>false</VALUE></SETTING>                <SETTING><NAME>CacheSubprojects</NAME><VALUE>true</VALUE></SETTING>                <SETTING><NAME>UseThirdPartyDebugger</NAME><VALUE>false</VALUE></SETTING>                <SETTING><NAME>DebuggerCommandLine</NAME><VALUE></VALUE></SETTING>                <!-- Settings for "Debugger Target" panel -->                <SETTING><NAME>LogSystemMessages</NAME><VALUE>true</VALUE></SETTING>                <SETTING><NAME>AutoTargetDLLs</NAME><VALUE>false</VALUE></SETTING>                <SETTING><NAME>StopAtWatchpoints</NAME><VALUE>true</VALUE></SETTING>                <SETTING><NAME>PauseWhileRunning</NAME><VALUE>false</VALUE></SETTING>                <SETTING><NAME>PauseInterval</NAME><VALUE>5</VALUE></SETTING>                <SETTING><NAME>PauseUIFlags</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>AltExePath</NAME>                    <SETTING><NAME>Path</NAME><VALUE></VALUE></SETTING>                    <SETTING><NAME>PathFormat</NAME><VALUE>Generic</VALUE></SETTING>                    <SETTING><NAME>PathRoot</NAME><VALUE>Absolute</VALUE></SETTING>                </SETTING>                <SETTING><NAME>StopAtTempBPOnLaunch</NAME><VALUE>true</VALUE></SETTING>                <SETTING><NAME>CacheSymbolics</NAME><VALUE>true</VALUE></SETTING>                <SETTING><NAME>TempBPFunctionName</NAME><VALUE>main</VALUE></SETTING>                <SETTING><NAME>TempBPType</NAME><VALUE>false</VALUE></SETTING>                <PANELDATA><NAME>Remote Debug</NAME><VALUE>                    0003000000000000000000000D6904600D69430000000000000003000E397580                    0000000000000000000000000D69046000000000000000000000000000000000                    0000000000000000000000000000000000000000000000000000000000000000                    0000000000000000000000000000000000000000000000000000000000000000                    0000000000000000000000000000000000000000000000000000000000000000                    0000000000000000000000000000000000000000000000000000000000000000                    0000000000000000000000000000000000000000000000000000000000000000                    0000000000000000000000000000000000000000000000000000000000000000                    0000000000000000000000000000000000000000000000000000000000000000                    0000000000000000000000000000000000000000000000000000000000000000                    0000000000000000000000000000000000000000000000000000000000000000                    0000000000000000000000000000000000000000000000000000000000000000                    0000000000000000000000000000000000000000000000000000000000000000                    0000000000000000000000000000000000000000000000000000000000000000                    0000000000000000000000000000000000000000000000000000000000000000                    0000000000000000000000000000000000000000000000000000000000000000                    0000000000000000000000000000000000000000000000000000000000000000                    0000000000000000000000000000000000000000000000000000000000000000                    0000000000000000000000000000000000000000000000000000000000000000                    0000000000000000000000000000000000000000000000000000000000000000                    0000000000000000000000000000000000000000000000000000000000000000                    0000000000000000000000000000000000000000000000000000000000000000                    0000000000000000000000000000000000000000000000000000000000000000                    0000000000000000000000000000000000000000000000000000000000000000                    000000000000                </VALUE></PANELDATA>                <PANELDATA><NAME>Auto-target</NAME><VALUE>                    00010000                </VALUE></PANELDATA>                <!-- Settings for "Custom Keywords" panel -->                <SETTING><NAME>CustomColor1</NAME>                    <SETTING><NAME>Red</NAME><VALUE>0</VALUE></SETTING>                    <SETTING><NAME>Green</NAME><VALUE>32767</VALUE></SETTING>                    <SETTING><NAME>Blue</NAME><VALUE>0</VALUE></SETTING>                </SETTING>                <SETTING><NAME>CustomColor2</NAME>                    <SETTING><NAME>Red</NAME><VALUE>0</VALUE></SETTING>                    <SETTING><NAME>Green</NAME><VALUE>32767</VALUE></SETTING>                    <SETTING><NAME>Blue</NAME><VALUE>0</VALUE></SETTING>                </SETTING>                <SETTING><NAME>CustomColor3</NAME>                    <SETTING><NAME>Red</NAME><VALUE>0</VALUE></SETTING>                    <SETTING><NAME>Green</NAME><VALUE>32767</VALUE></SETTING>                    <SETTING><NAME>Blue</NAME><VALUE>0</VALUE></SETTING>                </SETTING>                <SETTING><NAME>CustomColor4</NAME>                    <SETTING><NAME>Red</NAME><VALUE>0</VALUE></SETTING>                    <SETTING><NAME>Green</NAME><VALUE>32767</VALUE></SETTING>                    <SETTING><NAME>Blue</NAME><VALUE>0</VALUE></SETTING>                </SETTING>                <!-- Settings for "68K CodeGen" panel -->                <SETTING><NAME>MWCodeGen_68K_codesize</NAME><VALUE>Small</VALUE></SETTING>                <SETTING><NAME>MWCodeGen_68K_structalignment</NAME><VALUE>MC68K</VALUE></SETTING>                <SETTING><NAME>MWCodeGen_68K_fp_mode</NAME><VALUE>SANE</VALUE></SETTING>                <SETTING><NAME>MWCodeGen_68K_code68020</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWCodeGen_68K_profiler</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWCodeGen_68K_mpwc</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWCodeGen_68K_fourbyteints</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWCodeGen_68K_IEEEdoubles</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWCodeGen_68K_fardata</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWCodeGen_68K_farvtables</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWCodeGen_68K_farstrings</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWCodeGen_68K_pcrelstrings</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWCodeGen_68K_macsbug</NAME><VALUE>New</VALUE></SETTING>                <SETTING><NAME>MWCodeGen_68K_a6frames</NAME><VALUE>1</VALUE></SETTING>                <!-- Settings for "68K Disassembler" panel -->                <SETTING><NAME>MWDisassembler_68K_showcode</NAME><VALUE>1</VALUE></SETTING>                <SETTING><NAME>MWDisassembler_68K_mix</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWDisassembler_68K_nohex</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWDisassembler_68K_showdata</NAME><VALUE>1</VALUE></SETTING>                <SETTING><NAME>MWDisassembler_68K_showexceptions</NAME><VALUE>1</VALUE></SETTING>                <SETTING><NAME>MWDisassembler_68K_showsym</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWDisassembler_68K_shownames</NAME><VALUE>1</VALUE></SETTING>                <!-- Settings for "68K Global Optimizer" panel -->                <SETTING><NAME>GlobalOptimizer_68K_optimizationlevel</NAME><VALUE>Level0</VALUE></SETTING>                <SETTING><NAME>GlobalOptimizer_68K_optfor</NAME><VALUE>Speed</VALUE></SETTING>                <!-- Settings for "68K Linker" panel -->                <SETTING><NAME>MWLinker_68K_linksym</NAME><VALUE>1</VALUE></SETTING>                <SETTING><NAME>MWLinker_68K_symfullpath</NAME><VALUE>1</VALUE></SETTING>                <SETTING><NAME>MWLinker_68K_linksingle</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWLinker_68K_fastlink</NAME><VALUE>1</VALUE></SETTING>                <SETTING><NAME>MWLinker_68K_generateMap</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWLinker_68K_nolinkwarnings</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWLinker_68K_glueintosegone</NAME><VALUE>1</VALUE></SETTING>                <SETTING><NAME>MWLinker_68K_dontdeadstripinitcode</NAME><VALUE>0</VALUE></SETTING>                <!-- Settings for "68K Project" panel -->                <SETTING><NAME>MWProject_68K_type</NAME><VALUE>Application</VALUE></SETTING>                <SETTING><NAME>MWProject_68K_outfile</NAME><VALUE>a.out</VALUE></SETTING>                <SETTING><NAME>MWProject_68K_symfilename</NAME><VALUE></VALUE></SETTING>                <SETTING><NAME>MWProject_68K_filecreator</NAME><VALUE>1061109567</VALUE></SETTING>                <SETTING><NAME>MWProject_68K_filetype</NAME><VALUE>1095782476</VALUE></SETTING>                <SETTING><NAME>MWProject_68K_size</NAME><VALUE>384</VALUE></SETTING>                <SETTING><NAME>MWProject_68K_flags</NAME><VALUE>22656</VALUE></SETTING>                <SETTING><NAME>MWProject_68K_rsrcheader</NAME><VALUE>Standard</VALUE></SETTING>                <SETTING><NAME>MWProject_68K_rsrcname</NAME><VALUE></VALUE></SETTING>                <SETTING><NAME>MWProject_68K_rsrctype</NAME><VALUE>1061109567</VALUE></SETTING>                <SETTING><NAME>MWProject_68K_rsrcid</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWProject_68K_rsrcmulti</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWProject_68K_rsrcstore</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWProject_68K_rsrcmerge</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWProject_68K_rsrcflags</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWProject_68K_a4</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWProject_68K_minsize</NAME><VALUE>384</VALUE></SETTING>                <SETTING><NAME>MWProject_68K_rsrcsegtype</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWProject_68K_cfm68kcodegen</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWProject_68K_stacksize</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWProject_68K_thedebugger</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWProject_68K_rsrc_custom</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWProject_68K_is_rseg_app</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWProject_68K_is_pilot_lib</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWProject_68K_pilot_main_entry</NAME><VALUE></VALUE></SETTING>                <!-- Settings for "C/C++ Compiler" panel -->                <SETTING><NAME>MWFrontEnd_C_cplusplus</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWFrontEnd_C_checkprotos</NAME><VALUE>1</VALUE></SETTING>                <SETTING><NAME>MWFrontEnd_C_arm</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWFrontEnd_C_trigraphs</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWFrontEnd_C_onlystdkeywords</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWFrontEnd_C_enumsalwaysint</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWFrontEnd_C_mpwpointerstyle</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWFrontEnd_C_prefixname</NAME><VALUE>MacHeaders.h</VALUE></SETTING>                <SETTING><NAME>MWFrontEnd_C_ansistrict</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWFrontEnd_C_mpwcnewline</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWFrontEnd_C_wchar_type</NAME><VALUE>1</VALUE></SETTING>                <SETTING><NAME>MWFrontEnd_C_enableexceptions</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWFrontEnd_C_dontreusestrings</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWFrontEnd_C_poolstrings</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWFrontEnd_C_dontinline</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWFrontEnd_C_useRTTI</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWFrontEnd_C_multibyteaware</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWFrontEnd_C_unsignedchars</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWFrontEnd_C_autoinline</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWFrontEnd_C_booltruefalse</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWFrontEnd_C_direct_to_som</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWFrontEnd_C_som_env_check</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWFrontEnd_C_alwaysinline</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWFrontEnd_C_inlinelevel</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWFrontEnd_C_ecplusplus</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWFrontEnd_C_objective_c</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWFrontEnd_C_defer_codegen</NAME><VALUE>0</VALUE></SETTING>                <!-- Settings for "C/C++ Warnings" panel -->                <SETTING><NAME>MWWarning_C_warn_illpragma</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWWarning_C_warn_emptydecl</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWWarning_C_warn_possunwant</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWWarning_C_warn_unusedvar</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWWarning_C_warn_unusedarg</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWWarning_C_warn_extracomma</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWWarning_C_pedantic</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWWarning_C_warningerrors</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWWarning_C_warn_hidevirtual</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWWarning_C_warn_implicitconv</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWWarning_C_warn_notinlined</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWWarning_C_warn_structclass</NAME><VALUE>0</VALUE></SETTING>                <!-- Settings for "CFM68K" panel -->                <SETTING><NAME>MWCFM68K_exports</NAME><VALUE>None</VALUE></SETTING>                <SETTING><NAME>MWCFM68K_olddefversion</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWCFM68K_oldimpversion</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWCFM68K_currentversion</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWCFM68K_farthreshold</NAME><VALUE>256</VALUE></SETTING>                <SETTING><NAME>PCFM68K_sharedata</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWCFM68K_fragmentname</NAME><VALUE></VALUE></SETTING>                <SETTING><NAME>MWCFM68K_initname</NAME><VALUE></VALUE></SETTING>                <SETTING><NAME>MWCFM68K_mainname</NAME><VALUE>__start</VALUE></SETTING>                <SETTING><NAME>MWCFM68K_termname</NAME><VALUE></VALUE></SETTING>                <SETTING><NAME>MWCFM68K_libfolder</NAME><VALUE>0</VALUE></SETTING>                <SETTING><NAME>MWCFM68K_alignment</NAME><VALUE>Align_2</VALUE></SETTING>                <!-- Settings for "MacOS Merge Panel" panel -->                <SETTING><NAME>MWMerge_MacOS_projectType</NAME><VALUE>SharedLib</VALUE></SETTING>                <SETTING><NAME>MWMerge_MacOS_outputName</NAME><VALUE>Tclapplescript.shlb</VALUE></SETTING>                <SETTING><NAME>MWMerge_MacOS_outputCreator</NAME><VALUE>1415801932</VALUE></SETTING>                <SETTING><NAME>MWMerge_MacOS_outputType</NAME><VALUE>1936223330</VALUE></SETTING>                <SETTING><NAME>MWMerge_MacOS_suppressWarning</NAME><VALUE>1</VALUE></SETTING>                <SETTING><NAME>MWMerge_MacOS_copyFragments</NAME><VALUE>1</VALUE></SETTING>                <SETTING><NAME>MWMerge_MacOS_copyResources</NAME><VALUE>1</VALUE></SETTING>                <SETTING><NAME>MWMerge_MacOS_skipResources</NAME> 